// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.13.0
// source: app/grpc/proto/sample.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	AdminService_ListRamEvents_FullMethodName  = "/goit.app.grpc.pb.AdminService/ListRamEvents"
	AdminService_UpsertRamEvent_FullMethodName = "/goit.app.grpc.pb.AdminService/UpsertRamEvent"
)

// AdminServiceClient is the client API for AdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AdminService
type AdminServiceClient interface {
	// ListRamEvents
	ListRamEvents(ctx context.Context, in *ListRamEventsRequest, opts ...grpc.CallOption) (*ListRamEventsResponse, error)
	// UpsertRamEvent
	UpsertRamEvent(ctx context.Context, in *UpsertRamEventRequest, opts ...grpc.CallOption) (*UpsertRamEventResponse, error)
}

type adminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminServiceClient(cc grpc.ClientConnInterface) AdminServiceClient {
	return &adminServiceClient{cc}
}

func (c *adminServiceClient) ListRamEvents(ctx context.Context, in *ListRamEventsRequest, opts ...grpc.CallOption) (*ListRamEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRamEventsResponse)
	err := c.cc.Invoke(ctx, AdminService_ListRamEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) UpsertRamEvent(ctx context.Context, in *UpsertRamEventRequest, opts ...grpc.CallOption) (*UpsertRamEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertRamEventResponse)
	err := c.cc.Invoke(ctx, AdminService_UpsertRamEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServiceServer is the server API for AdminService service.
// All implementations must embed UnimplementedAdminServiceServer
// for forward compatibility
//
// AdminService
type AdminServiceServer interface {
	// ListRamEvents
	ListRamEvents(context.Context, *ListRamEventsRequest) (*ListRamEventsResponse, error)
	// UpsertRamEvent
	UpsertRamEvent(context.Context, *UpsertRamEventRequest) (*UpsertRamEventResponse, error)
	mustEmbedUnimplementedAdminServiceServer()
}

// UnimplementedAdminServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAdminServiceServer struct {
}

func (UnimplementedAdminServiceServer) ListRamEvents(context.Context, *ListRamEventsRequest) (*ListRamEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRamEvents not implemented")
}
func (UnimplementedAdminServiceServer) UpsertRamEvent(context.Context, *UpsertRamEventRequest) (*UpsertRamEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertRamEvent not implemented")
}
func (UnimplementedAdminServiceServer) mustEmbedUnimplementedAdminServiceServer() {}

// UnsafeAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServiceServer will
// result in compilation errors.
type UnsafeAdminServiceServer interface {
	mustEmbedUnimplementedAdminServiceServer()
}

func RegisterAdminServiceServer(s grpc.ServiceRegistrar, srv AdminServiceServer) {
	s.RegisterService(&AdminService_ServiceDesc, srv)
}

func _AdminService_ListRamEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRamEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ListRamEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ListRamEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ListRamEvents(ctx, req.(*ListRamEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_UpsertRamEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertRamEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).UpsertRamEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_UpsertRamEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).UpsertRamEvent(ctx, req.(*UpsertRamEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminService_ServiceDesc is the grpc.ServiceDesc for AdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "goit.app.grpc.pb.AdminService",
	HandlerType: (*AdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListRamEvents",
			Handler:    _AdminService_ListRamEvents_Handler,
		},
		{
			MethodName: "UpsertRamEvent",
			Handler:    _AdminService_UpsertRamEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/grpc/proto/sample.proto",
}
