CREATE TABLE IF NOT EXISTS foos (
  foo_id BIGINT AUTO_INCREMENT PRIMARY KEY,
  foo_1 VARCHAR(100) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS bars (
  bar_id BIGINT AUTO_INCREMENT PRIMARY KEY,
  foo_id BIGINT NOT NULL,
  bar_1 VARCHAR(50) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE bars 
ADD CONSTRAINT fk_bars_to_foos 
FOREIGN KEY (foo_id) 
REFERENCES foos (foo_id) ON DELETE CASCADE;